import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/organisms/Header';
import useAuth from '@/utils/useAuth';

export const metadata: Metadata = {
  title: {
    default: 'クルマート - KuruMart',
    template: '%s - KuruMart',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: メモ化するとエラーをasync内で使用することができない旨のエラーが回避できるらしいので検討する。
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const user = await useAuth();
  return (
    <html lang="en">
      <body className="w-full h-[1200px] py-6 dark:bg-neutral bg-[#FAF9FB]">
        <Header userInfo={user} className="max-w-5xl mx-auto" />
        <main className="max-w-5xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
